site_name: Barelang63 Documentations
site_url: https://mydomain.org/mysite
theme:
  name: material
  features:
  - navigation.instant
  - navigation.instant.progress
  - navigation.instant.preview
  - navigation.tracking
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.expand
  # - toc.integrate
  - navigation.top
  - search.suggest
  - search.highlight
  - search.share
  
  palette: 
    primary: black

  logo: assets/logo.png

plugins:
  - search


nav:
  - HOME: index.md

  - VISION:
    - Record Menggunakan ZED Camera: VISION/record_zed.md

