site_name: Barelang63 Documentations
site_url: https://mydomain.org/mysite
repo_url: https://github.com/Barelang63-BRAIL/Barelang63-Dokumentasi.git
repo_name: Barelang63-BRAIL/Barelang63-Dokumentasi

theme:
  name: material
  
  features:
  - navigation.instant
  - navigation.instant.progress
  - navigation.instant.preview
  - navigation.tracking
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.expand
  - navigation.top
  - search.suggest
  - search.highlight
  - search.share
  
  palette: 
    primary: black
    scheme: slate

  logo: assets/logo.png

  icon:
    repo: fontawesome/brands/github
    
  favicon: images/logo.png

plugins:
  - search

  - git-revision-date-localized:
      enable_creation_date: true

  - git-committers:
      repository: Barelang63-BRAIL/Barelang63-Dokumentasi
      branch: main

nav:
  - HOME: index.md

  - VISION:
    - Record Menggunakan ZED Camera: VISION/record_zed.md
    - Penggunaan toolVision: VISION/toolVision.md
    - YOLO11 Custom Model: VISION/yolo_custom_dataset.md

  - INSTALLATION:
    - Install All Package Robot: INSTALL/install_all.md
    - Build rtdb2 Package Robot: INSTALL/rtdb2_build.md
    - Dummy Monitor: INSTALL/dummy_monitor.md
    - Install CUDA dan cuDNN: INSTALL/cuda_and_cudnn.md
    - Install ZED SDK: INSTALL/zed_sdk_install.md
    - Install OpenCV dengan Aktivasi Cuda: INSTALL/install_opencv.md
    - Install STM32CubeIDE: INSTALL/install_stm32cubeide.md
